// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUsersCreatedAfter(ctx context.Context, createdAt sql.NullTime) ([]User, error)
}

var _ Querier = (*Queries)(nil)
