package core

import (
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

var defCatchallHandler = func(c *Ctx) error {
	log.Info("Default CatchAll Handler, URL: ", c.Request.URL.String())
	c.Response.SetStatus(404)
	c.Response.Message = "Not found!"
	return nil
}

func newRouter(path string) *Router {
	return &Router{
		basePath: path,
	}
}

// Router is a router for the application.
type Router struct {
	groups []*Router
	routes []*Route

	basePath    string
	middlewares []Middleware
}

// Use adds a middleware to the router.
func (r *Router) Use(m Middleware) {
	r.middlewares = append(r.middlewares, m)
}

// GetBasePath returns the base path of the router.
func (r Router) GetBasePath() string {
	if len(r.basePath) > 1 {
		if string(r.basePath[len(r.basePath)-1]) != "/" {
			return fmt.Sprintf("%s/", r.basePath)
		}
	} else if r.basePath == "" {
		return "/"
	}
	return r.basePath
}

// GET adds a GET endpoint to the router.
func (r *Router) GET(path string, handler Handler, opt ...RouteOption) {
	r.addEndpoint(METHOD_GET, path, handler, opt...)
}

// POST adds a POST endpoint to the router.
func (r *Router) POST(path string, handler Handler, opt ...RouteOption) {
	r.addEndpoint(METHOD_POST, path, handler, opt...)
}

// PUT adds a PUT endpoint to the router.
func (r *Router) PUT(path string, handler Handler, opt ...RouteOption) {
	r.addEndpoint(METHOD_PUT, path, handler, opt...)
}

// DELETE adds a DELETE endpoint to the router.
func (r *Router) DELETE(path string, handler Handler, opt ...RouteOption) {
	r.addEndpoint(METHOD_DELETE, path, handler, opt...)
}

// OPTIONS adds an OPTIONS endpoint to the router.
func (r *Router) OPTIONS(path string, handler Handler, opt ...RouteOption) {
	r.addEndpoint(METHOD_OPTIONS, path, handler, opt...)
}

// Redirect adds a redirect to the router.
func (r *Router) Redirect(path, targetURL string, code int) {
	h := func(c *Ctx) error {
		c.Response.Redirect(targetURL, code)
		return nil
	}
	r.addEndpoint(METHOD_GET, path, h, WithOpenApiDisabled())
}

// TODO: Add a ReadMulti method to the CrudInterface and implement corresponding router functionality to allow fetching multiple resources based on criteria.
// TODO: Add BulkUpdate, BulkDelete, and BulkCreate methods to the CrudInterface and implement corresponding router functionalities for efficient batch operations.
// TODO: Implement a mechanism to allow setting individual RouteOptions for each endpoint generated by the CRUD function, overriding the general CRUD options.
type CrudInterface interface {
	CreateFunc(any) (any, error)
	ReadAllFunc() ([]any, error)
	ReadOneFunc(any) (any, error)
	UpdateFunc(any, any) (any, error)
	DeleteFunc(any) (any, error)
}

// Add full CreateReadUpdateDelete Endpoints, for the basePath and given CrudInterface.
// Only adding Endpoints, for defined functions in CrudInterface.
// RouteOptions will be applied to all, for individual Options will be added later.
// POST   {basePath}/{id} -> Create
// GET    {basePath}/     -> ReadAll
// GET    {basePath}/{id}	-> ReadOne
// PUT    {basePath}/{id}	-> Update
// DELETE {basePath}/{id} -> Delete
// func (r *Router) CRUD(basePath string, ci CrudInterface, opt ...RouteOption) {
// 	pathWithID := fmt.Sprintf("%s/{id}", basePath)
//
// 	if ci.CreateFunc != nil {
// 		r.addEndpoint(METHOD_POST, pathWithID, ci.CreateFunc, opt...)
// 	}
// }

// StaticSevFileConfig holds the configuration for serving a static file.
type StaticSevFileConfig struct {
	preLoad    bool
	contentType string
}

// StaticServFileOption is a function that configures a StaticSevFileConfig.
type StaticServFileOption func(*StaticSevFileConfig)

// NewStaticServeFileConfig creates a new StaticSevFileConfig.
func NewStaticServeFileConfig(opts ...StaticServFileOption) *StaticSevFileConfig {
	c := &StaticSevFileConfig{
		preLoad:    true,
		contentType: "",
	}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

// WithPreCache caches the file content in memory.
func WithPreLoad() StaticServFileOption {
	// Read the file content once when the handler is created.
	// This is efficient for files that don't change frequently.
	return func(c *StaticSevFileConfig) {
		c.preLoad = true
	}
}

// WithContentType sets the content type of the file.
func WithContentType(contentType string) StaticServFileOption {
	return func(c *StaticSevFileConfig) {
		c.contentType = contentType
	}
}

// ServeStaticFile serves a static file.
func (r *Router) ServeStaticFile(urlPath, filePath string, opt ...StaticServFileOption) error {
	config := NewStaticServeFileConfig(opt...)
	absFilePath, err := filepath.Abs(filePath)

	if config.preLoad {
		if err != nil {
			log.Errorf("Error resolving absolute path for static file %s: %v", filePath, err)
			return err
		}

		log.Debugf("Attempting to serve static file from absolute path: %s", absFilePath)

		if _, err := os.Stat(absFilePath); os.IsNotExist(err) {
			err = fmt.Errorf("static file '%s' does not exist. Please ensure the file exists", absFilePath)
			log.Error(err)
			return err
		}

		content, err := os.ReadFile(absFilePath)
		if err != nil {
			err = fmt.Errorf("static file '%s' exists, but is not readable: %w", absFilePath, err)
			log.Error(err)
			return err
		}

		h := func(c *Ctx) error {
			c.Response.SetStatus(200)
			c.Response.SetData(content)
			c.Response.AddHeader("Content-Type", config.contentType)
			return nil
		}

		r.addEndpoint(
			METHOD_GET,
			urlPath,
			h,
			WithOpenApiDisabled(),
		)
	} else {
		h := func(c *Ctx) error {
			if err != nil {
				log.Errorf("Error resolving absolute path for static file %s: %v", filePath, err)
				return err
			}

			if _, err := os.Stat(absFilePath); os.IsNotExist(err) {
				err = fmt.Errorf("static file '%s' does not exist. Please ensure the file exists", absFilePath)
				log.Error(err)

				c.Response.SetStatus(404)
				c.Response.SetMessage("File not found... Please double-check the URL and try again.")
				return err
			}

			content, err := os.ReadFile(absFilePath)
			if err != nil {
				err = fmt.Errorf("static file '%s' exists, but is not readable: %w", absFilePath, err)
				log.Error(err)

				c.Response.SetStatus(500)
				c.Response.SetMessage("File was found, but is not readable... Please try again later, if it persists, contact the administrator.")
				return nil
			}

			c.Response.SetStatus(200)
			c.Response.SetData(content)
			c.Response.AddHeader("Content-Type", config.contentType)
			return nil
		}

		r.addEndpoint(
			METHOD_GET,
			urlPath,
			h,
			WithOpenApiDisabled(),
		)
	}

	return nil
}

// TODO: Rethink and reimplement ServeStaticDir to leverage more of the framework's features, such as middleware, routing, and context handling, instead of directly using http.FileServer.
func (r *Router) ServeStaticDir(urlPath, dirPath string, a App) {
	fs := http.FileServer(http.Dir(dirPath))
	// Ensure the pattern ends with / to avoid conflicts with method-specific patterns
	pattern := urlPath
	if !strings.HasSuffix(pattern, "/") {
		pattern += "/"
	}

	// Use wildcard patterns to match all paths under the directory
	// In Go 1.22+, we need {path...} for wildcard matching
	getPattern := "GET " + pattern + "{path...}"
	headPattern := "HEAD " + pattern + "{path...}"

	h := func(w http.ResponseWriter, r *http.Request) {
		// Strip the URL prefix to match the file system path
		http.StripPrefix(urlPath, fs).ServeHTTP(w, r)
	}

	a.handler.HandleFunc(getPattern, h)
	a.handler.HandleFunc(headPattern, h)
}

func (r *Router) routeExists(path string) int {
	// Checks if route exists and returns the index. If false -1 is returned.
	for i, route := range r.routes {
		if route.path == path {
			return i
		}
	}

	return -1
}

func (r *Router) addEndpoint(m RequestMethod, p string, h Handler, opt ...RouteOption) {
	routeConfig := NewRouteOptionConfig(opt...)
	routeIndex := r.routeExists(p)

	if routeIndex == -1 {
		var endpoints []Endpoint
		if p != "/" {
			optionEP := Endpoint{
				method: METHOD_OPTIONS,
				handleFunc: func(c *Ctx) error {
					c.Response.SetStatus(http.StatusOK)
					return nil
				},
				routeOptionConfig: RouteOptionConfig{},
			}
			endpoints = []Endpoint{optionEP}
		} else {
			endpoints = []Endpoint{}
		}

		r.routes = append(r.routes, &Route{
			basePath:  p,
			path:      fmt.Sprint(r.basePath, p),
			endpoints: endpoints,
		})

		routeIndex = len(r.routes) - 1
	}

	// Prevent adding duplicate OPTIONS endpoint if it already exists
	if m == METHOD_OPTIONS {
		for _, ep := range r.routes[routeIndex].endpoints {
			if ep.method == METHOD_OPTIONS {
				return
			}
		}
	}

	r.routes[routeIndex].endpoints = append(r.routes[routeIndex].endpoints, Endpoint{
		method:            m,
		handleFunc:        h,
		routeOptionConfig: *routeConfig,
		middlewares:       routeConfig.middlewares,
	})
}
