package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/bata94/apiright/pkg/core"
	"gopkg.in/yaml.v3"
)

type OpenAPIGenerator struct {
	genSuffix string
	logger    core.Logger
}

func NewOpenAPIGenerator(genSuffix string, logger core.Logger) *OpenAPIGenerator {
	return &OpenAPIGenerator{
		genSuffix: genSuffix,
		logger:    logger,
	}
}

type OpenAPISpec struct {
	OpenAPI    string                 `yaml:"openapi"`
	Info       OpenAPIInfo            `yaml:"info"`
	Servers    []OpenAPIServer        `yaml:"servers,omitempty"`
	Paths      map[string]OpenAPIPath `yaml:"paths"`
	Components OpenAPIComponents      `yaml:"components"`
}

type OpenAPIInfo struct {
	Title       string `yaml:"title"`
	Version     string `yaml:"version"`
	Description string `yaml:"description,omitempty"`
	Contact     *struct {
		Name  string `yaml:"name,omitempty"`
		URL   string `yaml:"url,omitempty"`
		Email string `yaml:"email,omitempty"`
	} `yaml:"contact,omitempty"`
	License *struct {
		Name string `yaml:"name"`
		URL  string `yaml:"url,omitempty"`
	} `yaml:"license,omitempty"`
}

type OpenAPIServer struct {
	URL         string `yaml:"url"`
	Description string `yaml:"description,omitempty"`
}

type OpenAPIPath struct {
	Get    *OpenAPIOperation `yaml:"get,omitempty"`
	Post   *OpenAPIOperation `yaml:"post,omitempty"`
	Put    *OpenAPIOperation `yaml:"put,omitempty"`
	Patch  *OpenAPIOperation `yaml:"patch,omitempty"`
	Delete *OpenAPIOperation `yaml:"delete,omitempty"`
}

type OpenAPIOperation struct {
	Summary     string                     `yaml:"summary,omitempty"`
	Description string                     `yaml:"description,omitempty"`
	Tags        []string                   `yaml:"tags,omitempty"`
	Parameters  []OpenAPIParameter         `yaml:"parameters,omitempty"`
	RequestBody *OpenAPIRequestBody        `yaml:"requestBody,omitempty"`
	Responses   map[string]OpenAPIResponse `yaml:"responses"`
}

type OpenAPIParameter struct {
	Name        string         `yaml:"name"`
	In          string         `yaml:"in"`
	Required    bool           `yaml:"required,omitempty"`
	Description string         `yaml:"description,omitempty"`
	Schema      *OpenAPISchema `yaml:"schema,omitempty"`
}

type OpenAPIRequestBody struct {
	Required    bool                        `yaml:"required,omitempty"`
	Description string                      `yaml:"description,omitempty"`
	Content     map[string]OpenAPIMediaType `yaml:"content"`
}

type OpenAPIMediaType struct {
	Schema  *OpenAPISchema `yaml:"schema,omitempty"`
	Example any            `yaml:"example,omitempty"`
}

type OpenAPIResponse struct {
	Description string                      `yaml:"description"`
	Content     map[string]OpenAPIMediaType `yaml:"content,omitempty"`
}

type OpenAPIComponents struct {
	Schemas map[string]OpenAPISchema `yaml:"schemas"`
}

type OpenAPISchema struct {
	Type       string                   `yaml:"type,omitempty"`
	Properties map[string]OpenAPISchema `yaml:"properties,omitempty"`
	Required   []string                 `yaml:"required,omitempty"`
	Items      *OpenAPISchema           `yaml:"items,omitempty"`
	Format     string                   `yaml:"format,omitempty"`
	Example    any                      `yaml:"example,omitempty"`
}

func (g *OpenAPIGenerator) Generate(schema *core.Schema, ctx *core.GenerationContext) error {
	spec := g.buildSpec(schema, ctx)

	// Create gen/openapi directory
	openapiDir := ctx.Join(ctx.ProjectDir, "gen", "openapi")
	if err := os.MkdirAll(openapiDir, 0755); err != nil {
		return fmt.Errorf("failed to create openapi directory: %w", err)
	}

	// Generate YAML spec
	yamlPath := filepath.Join(openapiDir, "openapi.yaml")
	if err := g.writeYAML(spec, yamlPath); err != nil {
		return fmt.Errorf("failed to write YAML spec: %w", err)
	}

	// Generate JSON spec
	jsonPath := filepath.Join(openapiDir, "openapi.json")
	if err := g.writeJSON(spec, jsonPath); err != nil {
		return fmt.Errorf("failed to write JSON spec: %w", err)
	}

	g.logger.Info("Generated OpenAPI specs", "yaml", yamlPath, "json", jsonPath)
	return nil
}

func (g *OpenAPIGenerator) buildSpec(schema *core.Schema, ctx *core.GenerationContext) *OpenAPISpec {
	spec := &OpenAPISpec{
		OpenAPI: "3.0.3",
		Info: OpenAPIInfo{
			Title:       "APIRight API",
			Version:     "1.0.0",
			Description: "API generated by APIRight framework",
		},
		Servers: []OpenAPIServer{
			{URL: "http://localhost:8080", Description: "Development server"},
		},
		Paths:      make(map[string]OpenAPIPath),
		Components: OpenAPIComponents{Schemas: make(map[string]OpenAPISchema)},
	}

	// Generate paths and schemas for each table
	for _, table := range schema.Tables {
		tableName := strings.TrimSuffix(table.Name, g.genSuffix)
		schemaName := core.ToPascalCase(tableName)

		// Add schema definition
		spec.Components.Schemas[schemaName] = g.buildSchema(table)

		// Add CRUD paths
		basePath := "/v1/" + tableName

		// GET /v1/{table} - List
		listOp := g.buildListOperation(schemaName, table)
		createOp := g.buildCreateOperation(schemaName, table)
		spec.Paths[basePath] = OpenAPIPath{
			Get:  listOp,
			Post: createOp,
		}

		// GET/PUT/DELETE /v1/{table}/{id}
		getOp := g.buildGetOperation(schemaName, table)
		updateOp := g.buildUpdateOperation(schemaName, table)
		deleteOp := g.buildDeleteOperation(schemaName, table)
		spec.Paths[basePath+"/{id}"] = OpenAPIPath{
			Get:    getOp,
			Put:    updateOp,
			Delete: deleteOp,
		}
	}

	return spec
}

func (g *OpenAPIGenerator) buildSchema(table core.Table) OpenAPISchema {
	schema := OpenAPISchema{
		Type:       "object",
		Properties: make(map[string]OpenAPISchema),
	}

	for _, col := range table.Columns {
		prop := OpenAPISchema{
			Type: core.SQLTypeToOpenAPI(col.Type),
		}
		if col.Nullable {
			prop.Type = "null, " + prop.Type
		}
		schema.Properties[core.ToPascalCase(col.Name)] = prop

		if !col.Nullable && !col.AutoIncrement {
			schema.Required = append(schema.Required, core.ToPascalCase(col.Name))
		}
	}

	return schema
}

func (g *OpenAPIGenerator) buildListOperation(schemaName string, table core.Table) *OpenAPIOperation {
	return &OpenAPIOperation{
		Summary:     fmt.Sprintf("List all %s", schemaName),
		Description: fmt.Sprintf("Returns a paginated list of %s", schemaName),
		Tags:        []string{schemaName},
		Parameters: []OpenAPIParameter{
			{Name: "limit", In: "query", Description: "Maximum number of items to return", Schema: &OpenAPISchema{Type: "integer"}},
			{Name: "offset", In: "query", Description: "Number of items to skip", Schema: &OpenAPISchema{Type: "integer"}},
		},
		Responses: map[string]OpenAPIResponse{
			"200": {
				Description: "Successful response",
				Content: map[string]OpenAPIMediaType{
					"application/json": {Schema: &OpenAPISchema{Type: "array", Items: &OpenAPISchema{Type: "object"}}},
					"application/xml":  {Schema: &OpenAPISchema{Type: "array", Items: &OpenAPISchema{Type: "object"}}},
					"application/yaml": {Schema: &OpenAPISchema{Type: "array", Items: &OpenAPISchema{Type: "object"}}},
				},
			},
		},
	}
}

func (g *OpenAPIGenerator) buildCreateOperation(schemaName string, table core.Table) *OpenAPIOperation {
	return &OpenAPIOperation{
		Summary:     fmt.Sprintf("Create a new %s", schemaName),
		Description: fmt.Sprintf("Creates a new %s record", schemaName),
		Tags:        []string{schemaName},
		RequestBody: &OpenAPIRequestBody{
			Required:    true,
			Description: "The " + schemaName + " to create",
			Content: map[string]OpenAPIMediaType{
				"application/json": {
					Schema:  &OpenAPISchema{Type: "object", Properties: g.getInputProperties(table)},
					Example: g.getCreateExample(table),
				},
				"application/xml": {
					Schema: &OpenAPISchema{Type: "object", Properties: g.getInputProperties(table)},
				},
				"application/yaml": {
					Schema: &OpenAPISchema{Type: "object", Properties: g.getInputProperties(table)},
				},
			},
		},
		Responses: map[string]OpenAPIResponse{
			"201": {
				Description: "Created successfully",
				Content: map[string]OpenAPIMediaType{
					"application/json": {Schema: &OpenAPISchema{Type: "object"}},
				},
			},
		},
	}
}

func (g *OpenAPIGenerator) buildGetOperation(schemaName string, table core.Table) *OpenAPIOperation {
	return &OpenAPIOperation{
		Summary:     fmt.Sprintf("Get %s by ID", schemaName),
		Description: fmt.Sprintf("Returns a single %s by its ID", schemaName),
		Tags:        []string{schemaName},
		Parameters: []OpenAPIParameter{
			{Name: "id", In: "path", Required: true, Description: "The ID of the " + schemaName, Schema: &OpenAPISchema{Type: "string"}},
		},
		Responses: map[string]OpenAPIResponse{
			"200": {
				Description: "Successful response",
				Content: map[string]OpenAPIMediaType{
					"application/json": {Schema: &OpenAPISchema{Type: "object"}},
					"application/xml":  {Schema: &OpenAPISchema{Type: "object"}},
					"application/yaml": {Schema: &OpenAPISchema{Type: "object"}},
				},
			},
			"404": {Description: "Not found"},
		},
	}
}

func (g *OpenAPIGenerator) buildUpdateOperation(schemaName string, table core.Table) *OpenAPIOperation {
	return &OpenAPIOperation{
		Summary:     fmt.Sprintf("Update %s", schemaName),
		Description: fmt.Sprintf("Updates an existing %s record", schemaName),
		Tags:        []string{schemaName},
		Parameters: []OpenAPIParameter{
			{Name: "id", In: "path", Required: true, Description: "The ID of the " + schemaName, Schema: &OpenAPISchema{Type: "string"}},
		},
		RequestBody: &OpenAPIRequestBody{
			Required:    true,
			Description: "The " + schemaName + " data to update",
			Content: map[string]OpenAPIMediaType{
				"application/json": {Schema: &OpenAPISchema{Type: "object", Properties: g.getInputProperties(table)}},
				"application/xml":  {Schema: &OpenAPISchema{Type: "object", Properties: g.getInputProperties(table)}},
				"application/yaml": {Schema: &OpenAPISchema{Type: "object", Properties: g.getInputProperties(table)}},
			},
		},
		Responses: map[string]OpenAPIResponse{
			"200": {Description: "Updated successfully"},
			"404": {Description: "Not found"},
		},
	}
}

func (g *OpenAPIGenerator) buildDeleteOperation(schemaName string, table core.Table) *OpenAPIOperation {
	return &OpenAPIOperation{
		Summary:     fmt.Sprintf("Delete %s", schemaName),
		Description: fmt.Sprintf("Deletes a %s record", schemaName),
		Tags:        []string{schemaName},
		Parameters: []OpenAPIParameter{
			{Name: "id", In: "path", Required: true, Description: "The ID of the " + schemaName, Schema: &OpenAPISchema{Type: "string"}},
		},
		Responses: map[string]OpenAPIResponse{
			"204": {Description: "Deleted successfully"},
			"404": {Description: "Not found"},
		},
	}
}

func (g *OpenAPIGenerator) getInputProperties(table core.Table) map[string]OpenAPISchema {
	props := make(map[string]OpenAPISchema)
	for _, col := range table.Columns {
		if col.AutoIncrement {
			continue
		}
		props[core.ToPascalCase(col.Name)] = OpenAPISchema{
			Type: core.SQLTypeToOpenAPI(col.Type),
		}
	}
	return props
}

func (g *OpenAPIGenerator) getCreateExample(table core.Table) map[string]any {
	example := make(map[string]any)
	for _, col := range table.Columns {
		if col.AutoIncrement {
			continue
		}
		example[core.ToPascalCase(col.Name)] = core.GetExampleValue(col.Type)
	}
	return example
}

func (g *OpenAPIGenerator) writeYAML(spec *OpenAPISpec, path string) error {
	data, err := yaml.Marshal(spec)
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0644)
}

func (g *OpenAPIGenerator) writeJSON(spec *OpenAPISpec, path string) error {
	data, err := yaml.Marshal(spec)
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0644)
}
