-- Generated CRUD queries for table users
-- This file is auto-generated by APIRight. Do not edit directly.
-- Use the queries/ directory for custom queries.

-- Get
-- name: GetUser_ar_gen :one
SELECT id, name, email, created_at, updated_at FROM users WHERE id = ? LIMIT 1;

-- List
-- name: ListUser_ar_gen :many
SELECT id, name, email, created_at, updated_at FROM users ORDER BY id LIMIT ? OFFSET ?;

-- Create
-- name: CreateUser_ar_gen :one
INSERT INTO users (name, email, created_at, updated_at) VALUES (?, ?, ?, ?) RETURNING id, name, email, created_at, updated_at;

-- Update
-- name: UpdateUser_ar_gen :one
UPDATE users SET name = ?, email = ?, created_at = ?, updated_at = ? WHERE id = ? RETURNING id, name, email, created_at, updated_at;

-- Delete
-- name: DeleteUser_ar_gen :exec
DELETE FROM users WHERE id = ?;

