name: Release CLI Tool

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on new tags like v1.0.0

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' # Use your desired Go version

      - name: Set up Just
        uses: extractions/setup-just@v3
        with:
          just-version: '^1.42.4'

      - name: Build temp cli
        run: just build

      - name: Run pre-release checks
        run: just pre-release

      - name: Build for Linux AMD64
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-s -w" -o apiright-cli-linux-amd64 ./cmd/apiright-cli
      - name: Build for Windows AMD64
        run: |
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-s -w" -o apiright-cli-windows-amd64.exe ./cmd/apiright-cli
      - name: Build for macOS AMD64
        run: |
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-s -w" -o apiright-cli-darwin-amd64 ./cmd/apiright-cli
      - name: Build for macOS ARM64
        run: |
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -ldflags "-s -w" -o apiright-cli-darwin-arm64 ./cmd/apiright-cli

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            apiright-cli-linux-amd64
            apiright-cli-windows-amd64.exe
            apiright-cli-darwin-amd64
            apiright-cli-darwin-arm64
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
